# Generated by Django 4.2.3 on 2023-07-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'managed': True, 'ordering': ['-publ'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментари'},
        ),
        migrations.AddIndex(
            model_name='comments',
            index=models.Index(fields=['-publ'], name='news_commen_publ_c60821_idx'),
        ),
    ]
